flyway.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require

flyway.user=syntra_migrator.mdxsybudkorrvmojqowx
flyway.password=Test12345

flyway.locations=filesystem:packages/db/migrations

flyway.placeholders.app_role=syntra_app
flyway.placeholders.relay_role=syntra_relay
flyway.placeholders.migrator_role=syntra_migrator

flyway.validateMigrationNaming=true
flyway.cleanDisabled=true