flyway.url=jdbc:postgresql://db.mdxsybudkorrvmojqowx.supabase.co:5432/postgres
flyway.user=postgres
flyway.password=87sonu90@M!

flyway.locations=filesystem:packages/db/migrations

flyway.placeholders.app_role=syntra_app
flyway.placeholders.relay_role=syntra_relay
flyway.placeholders.migrator_role=syntra_migrator

flyway.validateMigrationNaming=true
flyway.cleanDisabled=true